CREATE DATABASE IF NOT EXISTS weatherdb;
USE weatherdb;


CREATE TABLE IF NOT EXISTS weather_history (
id INT AUTO_INCREMENT PRIMARY KEY,
city VARCHAR(100) NOT NULL,
temperature VARCHAR(50),
description VARCHAR(255),
searched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);